try {
   try {
      console.log(e)
      
   } catch (e) {
      
   }
   console.log('weee')
} catch (error) {
   console.log(error, 'huh')
}